Repository profclems/glab, pull requests merged in 2020-11, with the labels that each got.

#288 Remove empty alias for check-update
  commands/update/checkupdate.go
Labels: size/XS

#289 docs: update readme
  .all-contributorsrc
  README.md
Labels: size/L

#290 style: change authentication instruction
  commands/cmdutils/remote_resolver.go
  commands/config/config.go
Labels: size/XS

#291 fix: mr merge priviledge
  commands/mr/diff/diff_test.go
  commands/mr/mrutils/mrutils.go
Labels: size/S

#293 docs: documentation link in readme
  README.md
Labels: size/XS

#296 Use `glab` formula from default Homebrew formulae
  .github/workflows/release.yml
  README.md
Labels: size/S

#284 feat: List user events
  commands/root.go
  commands/user/events/events.go
  commands/user/user.go
  pkg/api/events.go
Labels: Feature, size/L

#298 fix(repo search): Remove argument expectations
  commands/project/search/project_search.go
Labels: size/XS

#302 docs(readme): Add KISS Linux install instructions.
  README.md
Labels: size/XS

#304 style: switch remaining commands to iostream package
  cmd/glab/main.go
  commands/label/create/label_create.go
  commands/label/list/label_list.go
  commands/mr/approve/mr_approve.go
  commands/mr/approvers/mr_approvers.go
  commands/mr/close/mr_close.go
  commands/mr/delete/mr_delete.go
  commands/mr/delete/mr_delete_test.go
  commands/mr/for/mr_for.go
  commands/mr/issues/mr_issues.go
  commands/mr/merge/mr_merge.go
  commands/mr/note/mr_note_create.go
  commands/mr/note/mr_note_create_test.go
  commands/mr/rebase/mr_rebase.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/subscribe/mr_subscribe_test.go
  commands/mr/todo/mr_todo.go
  commands/mr/unsubscribe/mr_unsubscribe.go
  commands/mr/unsubscribe/mr_unsubscribe_test.go
  commands/mr/update/mr_update.go
  commands/pipeline/ci/trace/pipeline_ci_trace.go
  commands/pipeline/ci/view/pipeline_ci_view.go
  commands/pipeline/delete/pipeline_delete.go
  commands/pipeline/list/pipeline_list.go
  commands/pipeline/run/pipeline_run.go
  commands/pipeline/status/pipeline_status.go
  commands/project/archive/repo_archive.go
  commands/project/contributors/repo_contributors.go
  commands/project/create/project_create.go
  commands/project/search/project_search.go
  commands/release/list/release_list.go
  commands/release/list/release_list_test.go
  commands/root.go
  commands/root_test.go
  commands/update/checkupdate.go
  commands/version/version.go
  commands/version/version_test.go
  go.mod
  internal/utils/iostreams.go
  internal/utils/terminal.go
Labels: size/L

#305 test: add test for tableprinter package
  pkg/tableprinter/table_printer.go
  pkg/tableprinter/table_printer_test.go
  pkg/text/text_test.go
  pkg/text/truncate_test.go
Labels: size/L

#306 docs: Update README.md
  Makefile
  README.md
Labels: size/S

#303 feat(mr for): Add flag `--with-labels`
  commands/mr/for/mr_for.go
Labels: enhancement, size/XS

#308 fix incorrect version info on check-update
  cmd/glab/main.go
  commands/root.go
  commands/update/check_update.go
  commands/update/check_update_test.go
  commands/update/checkupdate.go
  commands/update/checkupdate_test.go
  commands/update/update.go
  commands/update/update_test.go
  go.mod
Labels: size/L

#312 deprecate `glab config init` in favour of `glab auth login`
  commands/config/config.go
Labels: size/XS

#317 test: fix failing test on forks without 'profclems' namespace
  commands/cmdtest/helper.go
Labels: size/S

#316 feat: use branch name as title if no commits are available for mr autofill
  commands/mr/create/mr_create.go
Labels: size/M

#327 fix: git directory independent commands
  commands/auth/login/login.go
  commands/cmdutils/factory.go
  commands/pipeline/ci/trace/pipeline_ci_trace_test.go
  commands/project/clone/repo_clone.go
  internal/glinstance/host.go
  internal/glrepo/remote.go
  internal/glrepo/repo.go
  internal/utils/iostreams.go
  pkg/api/client.go
Labels: size/L

#315 fix(mr): Readd ability to close multiple MRs
  commands/mr/close/mr_close.go
  commands/mr/delete/mr_delete.go
  commands/mr/mrutils/mrutils.go
  commands/mr/reopen/mr_reopen.go
  go.mod
  go.sum
Labels: kind: fix, size/L

#328 feat(api): add api command to allow access to GitLab API
  commands/api/api.go
  commands/api/api_test.go
  commands/api/http.go
  commands/api/http_test.go
  commands/api/pagination.go
  commands/api/pagination_test.go
  commands/auth/login/login.go
  commands/cmdutils/factory.go
  commands/mr/diff/diff_test.go
  commands/project/clone/repo_clone.go
  commands/root.go
  go.mod
  go.sum
  pkg/api/client.go
Labels: kind: enhancement, size/XXL

#332 Ensure only $PATH is searched when switching to external commands
  Makefile
  commands/alias/expand/alias_expand.go
  go.mod
  go.sum
  internal/utils/terminal.go
  pkg/execext/lp.go
  pkg/execext/lp_test.go
  pkg/execext/lp_windows.go
  pkg/execext/testdata/PATH/git
  pkg/execext/testdata/PATH/git.bat
  pkg/execext/testdata/PATH/git.exe
  pkg/execext/testdata/cwd/git
  pkg/execext/testdata/cwd/git.bat
  pkg/execext/testdata/cwd/git.exe
Labels: kind: fix, size/L

#334 fix(ci view): Return error if no pipeline found
  commands/pipeline/ci/view/pipeline_ci_view.go
Labels: size/XS

#336 fix(ci): Remove OrderBy field from pipeline list options
  commands/pipeline/ci/trace/pipeline_ci_trace.go
  commands/pipeline/status/pipeline_status.go
  pkg/api/pipeline.go
Labels: kind: fix, size/S

#337 Add template support to mr create and issue create workflow
  .gitlab/issue_templates/Bug.md
  .gitlab/issue_templates/Feature Request.md
  .gitlab/merge_request_templates/Default.md
  commands/cmdutils/cmdutils.go
  commands/issue/board/create/issue_board_create.go
  commands/issue/create/issue_create.go
  commands/issue/create/issue_create_test.go
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
  commands/project/create/project_create.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_type.go
  internal/utils/manip.go
  pkg/prompt/prompt.go
  pkg/prompt/stubber.go
  pkg/surveyext/surveyext.go
Labels: kind: enhancement, size/XXL

#338 feat: add labels multiselect to issue create and mr create
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  commands/project/create/project_create.go
  internal/git/git.go
  pkg/prompt/prompt.go
  pkg/prompt/stubber.go
Labels: size/M
