Repository profclems/glab, pull requests merged in 2020-09, with the labels that each got.

#192 chore: setup test ci
  .github/workflows/go.yml
Labels: size/S

#195 fix: Migrate config dir to XDG_CONFIG_HOME
  internal/config/config.go
  internal/config/file.go
Labels: size/M

#199 fix: alias name conflicting core commands
  commands/alias_set.go
  commands/alias_set_test.go
  go.mod
  go.sum
  internal/config/config.go
Labels: size/M

#200 fix(config): Make SetEnv invalidate cache used by GetEnv
  internal/config/config.go
  internal/config/file.go
Labels: size/XS

#201 fix(config): SetEnv appends to gitignore every time
  internal/config/config.go
  internal/config/file.go
Labels: size/S

#202 fix: File content modification made a bit more safe and sane
  go.mod
  go.sum
  internal/config/config.go
  internal/config/file.go
Labels: size/M

#206 chore(ci): set up travis to run tests
  .travis.yml
  go.mod
  go.sum
Labels: size/M

#207 Revert "chore(ci): set up travis to run tests"
  .travis.yml
  go.mod
  go.sum
Labels: size/M

#208 chore(ci): travis tests
  .travis.yml
  go.mod
  go.sum
Labels: size/M

#209 test: add tests to core commands
  .gitignore
  commands/issue_close.go
  commands/issue_create.go
  commands/issue_create_test.go
  commands/issue_delete.go
  commands/issue_list.go
  commands/issue_note_create.go
  commands/issue_reopen.go
  commands/issue_subscribe.go
  commands/issue_unsubscribe.go
  commands/issue_view.go
  commands/label_create.go
  commands/label_list.go
  commands/mr_approve.go
  commands/mr_approvers.go
  commands/mr_close.go
  commands/mr_create.go
  commands/mr_create_test.go
  commands/mr_delete.go
  commands/mr_delete_test.go
  commands/mr_for.go
  commands/mr_issues.go
  commands/mr_list.go
  commands/mr_merge.go
  commands/mr_note_create.go
  commands/mr_rebase.go
  commands/mr_reopen.go
  commands/mr_revoke.go
  commands/mr_subscribe.go
  commands/mr_test.go
  commands/mr_todo.go
  commands/mr_unsubscribe.go
  commands/mr_update.go
  commands/mr_view.go
  commands/pipeline_ci_trace.go
  commands/pipeline_ci_view.go
  commands/pipeline_delete.go
  commands/pipeline_list.go
  commands/pipeline_status.go
  commands/release.go
  commands/release_list.go
  commands/repo.go
  go.mod
  go.sum
  internal/git/git.go
  internal/git/git_test.go
Labels: size/L

#212 fix(config): Use ioutil.WriteFile on Windows
  internal/config/config.go
  internal/config/writefile.go
  internal/config/writefile_windows.go
Labels: size/S

#214 feat: configuration enhancement
  .gitignore
  commands/config.go
  commands/config_test.go
  commands/root.go
  commands/root_test.go
  go.mod
  internal/config/config.go
  internal/utils/color.go
  test/testdata/test.glab-cli/config/.env
Labels: size/L

#215 feat: add support for shell completion
  .travis.yml
  commands/completion.go
  commands/completion_test.go
Labels: size/L

#216 test: test expand alias
  .travis.yml
  cmd/glab/main.go
  cmd/glab/main_test.go
  go.mod
  go.sum
Labels: size/L

#218 feat: add ability to create repo from current directory
  cmd/glab/main_test.go
  commands/alias_delete.go
  commands/issue.go
  commands/issue_list.go
  commands/issue_view.go
  commands/mr.go
  commands/mr_create.go
  commands/mr_list.go
  commands/mr_note_create_test.go
  commands/mr_view.go
  commands/mr_view_test.go
  commands/pipeline.go
  commands/pipeline_ci_trace.go
  commands/pipeline_ci_trace_test.go
  commands/pipeline_ci_view.go
  commands/pipeline_list.go
  commands/project.go
  commands/project_create.go
  commands/project_create_test.go
  commands/repo_contributors.go
  commands/root.go
  go.mod
  go.sum
  internal/git/git.go
  internal/git/git_test.go
  internal/manip/manip.go
Labels: size/XL

#220 feat: ability to create shell-executable aliases
  cmd/glab/main.go
  cmd/glab/main_test.go
  commands/alias_delete.go
  commands/alias_delete_test.go
  commands/alias_expand.go
  commands/alias_expand_test.go
  commands/alias_set.go
  commands/alias_set_test.go
  go.mod
  go.sum
  internal/browser/browser_test.go
Labels: size/XL

#221 feat: add ability to set git protocol
  cmd/glab/main.go
  commands/project.go
  commands/project_create.go
  commands/repo_clone.go
  commands/root.go
  commands/root_test.go
  commands/user.go
  go.mod
  go.sum
  internal/git/git.go
Labels: size/L

#226 feat: add `mr list` flag `mine`
  commands/mr_list.go
Labels: size/XS

#223 fix: better config package to enhance test and restructuring
  cmd/glab/main.go
  commands/pipeline_status.go
  commands/repo_archive.go
  go.mod
  go.sum
  internal/config/alias_config.go
  internal/config/config.go
  internal/config/config_file.go
  internal/config/config_file_test.go
  internal/config/config_migration.go
  internal/config/config_type.go
  internal/config/config_type_test.go
  internal/config/host_config.go
  internal/config/local_config.go
  internal/config/testing.go
Labels: size/XXL
