Repository profclems/glab, pull requests merged in 2020-10, with the labels that each got.

#235 style: Remove additional newline after version output
  commands/version/version.go
Labels: size/XS

#239 fix config auth check
  commands/cmdutils/cmdutils.go
  commands/config/config.go
  commands/root.go
Labels: size/M

#241 fix: avoid auth check on repo clone
  commands/project/clone/repo_clone.go
Labels: size/M

#244 fix: glab pipeline list always says "No pipelines..."
  commands/pipeline/pipelineutils/utils.go
Labels: size/XS

#240 feat: Add Update Sub-command to Issue Command
  commands/issue/issue.go
  commands/issue/update/issue_update.go
  commands/issue/update/issue_update_test.go
Labels: size/L

#250 feat: add command to create issue board
  commands/issue/board/board.go
  commands/issue/board/board_test.go
  commands/issue/board/create/issue_board_create.go
  commands/issue/board/create/issue_board_create_test.go
  commands/issue/issue.go
  pkg/api/board.go
Labels: size/L

#251 chore(ci): use golangci and codeql for linting and analysis
  .deepsource.toml
  .github/workflows/build_docs.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .golangci.yml
Labels: size/M

#245 feat: support "Run pipeline"
  commands/pipeline/pipeline.go
  commands/pipeline/run/pipeline_run.go
  pkg/api/pipeline.go
Labels: size/L

#255 feat: add issue board view command
  commands/issue/board/board.go
  commands/issue/board/view/issue_board_view.go
  commands/pipeline/ci/view/pipeline_ci_view.go
  commands/pipeline/pipelineutils/utils.go
  pkg/api/board.go
Labels: size/L

#257 Feature: mr list by asssignee
  commands/mr/list/mr_list.go
  pkg/api/merge_request.go
  pkg/api/user.go
Labels: size/M

#260 fix: Add Create Command to Label
  commands/label/create/label_create.go
  commands/label/label.go
Labels: size/XS

#261 enhance list table display
  commands/issue/issueutils/utils.go
  commands/issue/list/issue_list.go
  commands/label/list/label_list.go
  commands/mr/issues/mr_issues.go
  commands/mr/list/mr_list.go
  commands/mr/mrutils/mrutils.go
  commands/pipeline/list/pipeline_list.go
  commands/pipeline/pipelineutils/utils.go
  commands/pipeline/status/pipeline_status.go
  commands/project/search/project_search.go
  commands/release/list/release_list.go
  commands/release/list/release_list_test.go
  commands/release/releaseutils/releaseutils.go
  internal/utils/display.go
  pkg/api/default.go
  pkg/api/issue.go
  pkg/api/label.go
  pkg/api/merge_request.go
  pkg/api/pipeline.go
  pkg/api/release.go
  pkg/api/user.go
  pkg/tableprinter/table_printer.go
Labels: size/XL

#264 feat: detect MR for current branch
  cmd/glab/main.go
  commands/mr/approve/mr_approve.go
  commands/mr/approvers/mr_approvers.go
  commands/mr/close/mr_close.go
  commands/mr/create/mr_create_test.go
  commands/mr/delete/mr_delete.go
  commands/mr/delete/mr_delete_test.go
  commands/mr/issues/mr_issues.go
  commands/mr/merge/mr_merge.go
  commands/mr/mrutils/mrutils.go
  commands/mr/note/mr_note_create.go
  commands/mr/rebase/mr_rebase.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/subscribe/mr_subscribe_test.go
  commands/mr/todo/mr_todo.go
  commands/mr/unsubscribe/mr_unsubscribe.go
  commands/mr/unsubscribe/mr_unsubscribe_test.go
  commands/mr/update/mr_update.go
  commands/mr/view/mr_view.go
  pkg/tableprinter/table_printer.go
Labels: size/XL

#267 chore(build): add snap packaging
  snap/snapcraft.yaml
Labels: size/M

#271 feat: add pager support
  cmd/glab/main.go
  commands/alias/delete/alias_delete.go
  commands/alias/delete/alias_delete_test.go
  commands/alias/list/alias_list.go
  commands/alias/list/alias_list_test.go
  commands/alias/set/alias_set.go
  commands/alias/set/alias_set_test.go
  commands/cmdtest/helper.go
  commands/cmdutils/factory.go
  commands/completion/completion.go
  commands/completion/completion_test.go
  commands/config/config.go
  commands/config/config_test.go
  commands/issue/board/create/issue_board_create.go
  commands/issue/board/create/issue_board_create_test.go
  commands/issue/close/issue_close.go
  commands/issue/close/issue_close_test.go
  commands/issue/create/issue_create.go
  commands/issue/create/issue_create_test.go
  commands/issue/delete/issue_delete.go
  commands/issue/delete/issue_delete_test.go
  commands/issue/list/issue_list.go
  commands/issue/note/issue_note_create.go
  commands/issue/note/issue_note_create_test.go
  commands/issue/reopen/issue_reopen.go
  commands/issue/subscribe/issue_subscribe.go
  commands/issue/subscribe/issue_subscribe_test.go
  commands/issue/unsubscribe/issue_unsubscribe.go
  commands/issue/unsubscribe/issue_unsubscribe_test.go
  commands/issue/update/issue_update.go
  commands/issue/update/issue_update_test.go
  commands/issue/view/issue_view.go
  commands/issue/view/issue_view_test.go
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
  commands/mr/list/mr_list.go
  commands/mr/view/mr_view.go
  commands/mr/view/mr_view_test.go
  commands/pipeline/ci/lint/pipeline_ci_lint.go
  commands/root.go
  commands/root_test.go
  internal/utils/color.go
  internal/utils/iostreams.go
  internal/utils/utils.go
Labels: size/XXL

#275 fix(config): respect api_protocol in config
  cmd/glab/main.go
  commands/cmdutils/factory.go
  internal/glinstance/host.go
  internal/glinstance/host_test.go
  pkg/api/client.go
Labels: size/M

#278 feat: Add ability to mark branch to be deleted from update
  commands/mr/update/mr_update.go
Labels: size/XS

#277 feat: glab auth login
  .travis.yml
  cmd/glab/main.go
  commands/auth/auth.go
  commands/auth/login/login.go
  commands/auth/login/login_test.go
  commands/cmdutils/factory.go
  commands/root.go
  internal/config/config_type.go
  internal/utils/iostreams.go
  pkg/api/client.go
Labels: size/XL

#279 chore(ci): switch from to GitLab CI
  .gitlab-ci.yml
  .travis.yml
  internal/git/git_test.go
Labels: size/L

#281 feat: add mr diff command
  commands/mr/approvers/mr_approvers.go
  commands/mr/checkout/mr_checkout.go
  commands/mr/close/mr_close.go
  commands/mr/delete/mr_delete.go
  commands/mr/delete/mr_delete_test.go
  commands/mr/diff/diff.go
  commands/mr/diff/diff_test.go
  commands/mr/issues/mr_issues.go
  commands/mr/mr.go
  commands/mr/mrutils/mrutils.go
  commands/mr/note/mr_note_create.go
  commands/mr/rebase/mr_rebase.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/todo/mr_todo.go
  commands/mr/unsubscribe/mr_unsubscribe.go
  commands/mr/update/mr_update.go
  go.mod
  go.sum
  pkg/api/client.go
Labels: size/XL

#286 Mention issue instead of merge request in description. Closes #285.
  commands/mr/for/mr_for.go
Labels: size/XS
