Repository profclems/glab, pull requests merged in 2020-12, with the labels that each got.

#340 feat: add repo delete command
  commands/cmdutils/cmdutils.go
  commands/project/create/project_create.go
  commands/project/delete/delete.go
  commands/project/repo.go
  pkg/prompt/prompt.go
  pkg/prompt/stubber.go
Labels: size/L

#345 fix: mr create failure when templates are not available
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
Labels: kind: fix, size/S

#355 feat: add repo fork command
  commands/project/fork/fork.go
  commands/project/repo.go
  pkg/api/project.go
Labels: kind: enhancement, size/L

#357 chore(ci): github action workflow update
  .github/workflows/pr_move_to_in_progress.yml
  .github/workflows/pr_ready_for_review.yml
  .github/workflows/release.yml
  scripts/changelog
Labels: size/M

#352 ft(pipeline): Add variables flag for `pipeline run`
  commands/pipeline/run/pipeline_run.go
Labels: kind: enhancement, size/M

#360 fix(mr): Fix wrong usage of pull request
  commands/mr/view/mr_view.go
  commands/mr/view/mr_view_test.go
Labels: size/XS

#365 (chore): Clean up releases
  .goreleaser.yml
Labels: size/M

#367 ci: delete project automation workflow
  .github/workflows/pr_move_to_in_progress.yml
  .github/workflows/pr_ready_for_review.yml
Labels: size/M

#361 feat: Use user name for assignees
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  commands/mr/update/mr_update.go
Labels: size/M

#370 fix(issue): Check error on getting current user
  commands/issue/list/issue_list.go
Labels: kind: fix, size/XS

#371 chore: refactor mr view
  commands/mr/mrutils/mrutils.go
  commands/mr/view/mr_view.go
  internal/utils/iostreams.go
Labels: kind: Refactoring, kind: cleanup, size/L

#374 chore: create glab installer for windows using innosetup
  .github/workflows/release.yml
  scripts/setup_windows.iss
Labels: area: platform-packaging, platform: Windows, size/L

#375 chore(packaging): add installation guide for winget
  README.md
Labels: area: documentation, area: platform-packaging, platform: Windows, size/M

#378 docs: document multiple gitlab instances support
  README.md
Labels: size/XS

#363 test: fix tests
  .gitlab-ci.yml
  Makefile
  commands/auth/auth_test.go
  commands/ci/ci.go
  commands/ci/legacyci/pipeline_ci.go
  commands/ci/lint/lint.go
  commands/ci/lint/lint_test.go
  commands/ci/status/status.go
  commands/ci/trace/trace.go
  commands/ci/trace/trace_test.go
  commands/cmdtest/helper.go
  commands/mr/create/mr_create_test.go
  commands/mr/delete/mr_delete_test.go
  commands/mr/subscribe/mr_subscribe_test.go
  commands/mr/unsubscribe/mr_unsubscribe_test.go
  commands/project/clone/repo_clone_test.go
  commands/release/list/release_list_test.go
  commands/user/user_test.go
  pkg/api/board.go
  pkg/api/branch.go
  pkg/api/client.go
  pkg/api/events.go
  pkg/api/issue.go
  pkg/api/label.go
  pkg/api/merge_request.go
  pkg/api/pipeline.go
  pkg/api/project.go
  pkg/api/release.go
  pkg/api/user.go
Labels: kind: test, size/XL

#381 fix(cmd/mr/merge): don't print Default to true as Cobra already does
  commands/mr/merge/mr_merge.go
Labels: size/XS

#387 feat(cmd/mr/merge): show different message when merging after pipeline success
  commands/mr/merge/mr_merge.go
Labels: size/XS

#394 fix(internal/glrepo/resolver): don't use pointers to gitlab.Project{}
  internal/glrepo/resolver.go
Labels: size/XS

#398 fix(command/issue/update): add missing newline to Fprintf call
  commands/issue/update/issue_update.go
Labels: kind: fix, size/XS

#396 feat(cmd/issue/update): add --public and --confidential flags
  commands/issue/update/issue_update.go
Labels: cmd: issue, kind: enhancement, size/S

#392 chore: add alpine package support
  README.md
Labels: size/M

#401 Unlock discussion
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
Labels: size/S

#404 feat(commands/mr/create): add --repo support for --target-project
  commands/mr/create/mr_create.go
Labels: cmd: mr, kind: enhancement, size/S

#408 fix tracking br mr create
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
  internal/git/git.go
Labels: kind: fix, size/L

#411 feat: provide submit options for `mr create` and `issue create`
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/issue/create/issue_create_test.go
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
Labels: size/XL

#412 docs(readme): use official scoop main bucket
  README.md
Labels: area: documentation, area: platform-packaging, platform: Windows, size/XS

#413 fix: set tracking branch only if not set
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
  internal/git/git.go
Labels: size/S

#414 Rework BaseRepo from internal.glrepo.resolver
  internal/glrepo/resolver.go
Labels: kind: enhancement, size/M

#416 feat(commands/mr/create): fix logic for setting upstream branch
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
Labels: size/L

#410 glab-resolved = {base|head} support
  commands/mr/create/mr_create.go
  internal/glrepo/resolver.go
Labels: cmd: mr, core: Git, kind: enhancement, size/L

#418 fix(commands/mr/create): create merge request against headRepo
  commands/mr/create/mr_create.go
Labels: size/XS

#420 fix(commands/mr/close): print newline
  commands/mr/close/mr_close.go
Labels: size/XS

#427 fix(ISSUE_TEMPLATE/feature_request): turn explanation into comments
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS

#424 Fix deepsource woes
  cmd/gen-docs/docs.go
  commands/api/http.go
  commands/ci/ciutils/utils.go
  commands/ci/trace/trace.go
  commands/ci/view/view.go
  commands/issue/board/view/issue_board_view.go
  commands/mr/create/mr_create.go
  commands/project/archive/repo_archive.go
  internal/config/config_file.go
  internal/glrepo/resolver.go
  pkg/prompt/prompt.go
  pkg/surveyext/surveyext.go
Labels: size/M

#423 add --yes flag to mr create and issue create and fix a bug
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: size/S

#430 `issue create` and `mr create` escape
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: cmd: issue, cmd: mr, kind: fix, size/S

#437 fix(internal/glrepo/resolver): check for 'head' not 'head:'
  internal/glrepo/resolver.go
Labels: kind: fix, priority: high, size/XS

#438 feat(pkg/api/user): if given user is @me, translate to current user
  pkg/api/user.go
Labels: kind: enhancement, size/XS

#441 feat(commands/mr/mrutils): add OWNER:branch support
  commands/mr/mrutils/mrutils.go
Labels: cmd: issue, kind: enhancement, size/M

#444 remove extra space on PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#442 fix(pkg/api/pipeline): sort pipeline jobs using CreatedAt
  pkg/api/pipeline.go
Labels: kind: fix, size/M

#446 add support for interactively attaching milestones
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  pkg/api/milestone.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/M

#449 feat(commands/mr/create): prompt for labels with --autofill
  commands/mr/create/mr_create.go
Labels: kind: enhancement, size/XS

#451 implement asssigning milestone by its title
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  pkg/api/milestone.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/M

#454 fix: remotes error on issue create
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/issue/create/issue_create_test.go
  commands/mr/create/mr_create.go
Labels: kind: fix, size/M

#452 fix(command/cmdutils): return global ID from interactive prompt
  commands/cmdutils/cmdutils.go
Labels: size/XS

#453 feat: Interactive assignee
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/M

#456 fix: respect repo override
  commands/ci/trace/trace.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: kind: fix, size/M

#457 fix(commands/mr/create): make --yes prompt more concise
  commands/mr/create/mr_create.go
Labels: size/XS

#459 feat: simplify prompts with metadata prompt
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/L

#462 style: formalize message telling issue/mr was closed/reopened
  commands/issue/close/issue_close.go
  commands/issue/close/issue_close_test.go
  commands/issue/reopen/issue_reopen.go
  commands/mr/close/mr_close.go
  commands/mr/reopen/mr_reopen.go
Labels: kind: Refactoring, size/S

#469 Better `repo contributors` command
  commands/project/contributors/repo_contributors.go
Labels: cmd: repo/project, kind: enhancement, kind: fix, size/L

#464 feat: be more descriptive about what is done in `issue update` and `mr update`
  commands/issue/update/issue_update.go
  commands/issue/update/issue_update_test.go
  commands/mr/update/mr_update.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/M

#471 implement more flags for updating issues and merge requests
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/M

#473 fix deepsource bug risks
  commands/api/api.go
  commands/cmdutils/cmdutils.go
  commands/issue/board/view/issue_board_view.go
Labels: size/S

#475 test(internal/utils): add test for Pluralize
  internal/utils/utils_test.go
Labels: size/M

#478 Add `--label` and `--unlabel` flags to `mr update`
  commands/mr/update/mr_update.go
Labels: cmd: mr, kind: enhancement, size/S

#477 Allow comma-separated labels for `issue update`
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
Labels: cmd: issue, kind: enhancement, size/S
