Repository profclems/glab, pull requests merged in 2020-08, with the labels that each got.

#58 Fix command typo
  README.md
Labels: documentation

#72 Add help pages for each command
  cmd/glab/main.go
  cmd/glab/utils/help.go
  cmd/glab/utils/issue.go
  cmd/glab/utils/mr.go
  cmd/glab/utils/pipeline.go
  cmd/glab/utils/repo.go
  commands/issue.go
  commands/mr.go
  commands/pipeline.go
  commands/repo.go
  glab.go
Labels: documentation, enhancement

#99 fix: build_docs CI failure when no doc changes found.
  .github/workflows/build_docs.yml
Labels: size/XS

#104 Feat: Added pagination
  commands/issue_list.go
  commands/issue_view.go
  commands/label_list.go
  commands/mr_list.go
  commands/mr_view.go
  commands/pipeline_list.go
Labels: size/M

#107 feat(mr): add glab mr approvers command
  .gitignore
  commands/mr_approvers.go
Labels: Feature, size/M

#111 docs: update environment variables on README.md
  README.md
  docs/glab.md
  docs/glab_check-update.md
  docs/glab_config.md
  docs/glab_issue.md
  docs/glab_issue_close.md
  docs/glab_issue_create.md
  docs/glab_issue_delete.md
  docs/glab_issue_list.md
  docs/glab_issue_note.md
  docs/glab_issue_reopen.md
  docs/glab_issue_subscribe.md
  docs/glab_issue_unsubscribe.md
  docs/glab_issue_view.md
  docs/glab_label.md
  docs/glab_label_create.md
  docs/glab_label_list.md
  docs/glab_mr.md
  docs/glab_mr_approve.md
  docs/glab_mr_approvers.md
  docs/glab_mr_checkout.md
  docs/glab_mr_close.md
  docs/glab_mr_create.md
  docs/glab_mr_delete.md
  docs/glab_mr_issues.md
  docs/glab_mr_list.md
  docs/glab_mr_merge.md
  docs/glab_mr_note.md
  docs/glab_mr_rebase.md
  docs/glab_mr_reopen.md
  docs/glab_mr_revoke.md
  docs/glab_mr_subscribe.md
  docs/glab_mr_unsubscribe.md
  docs/glab_mr_update.md
  docs/glab_mr_view.md
  docs/glab_pipeline.md
  docs/glab_pipeline_ci.md
  docs/glab_pipeline_ci_lint.md
  docs/glab_pipeline_ci_trace.md
  docs/glab_pipeline_ci_view.md
  docs/glab_pipeline_delete.md
  docs/glab_pipeline_list.md
  docs/glab_pipeline_status.md
  docs/glab_repo.md
  docs/glab_repo_archive.md
  docs/glab_repo_clone.md
  docs/glab_repo_contributors.md
  docs/glab_version.md
  docs/index.md
Labels: size/L

#112 feat: add GLab logo README.md
  README.md
Labels: size/XS

#110 feat: Add release command
  commands/release.go
  commands/release_list.go
Labels: size/L

#142 refactor: Redirect all list printing to common utility
  commands/issue.go
  commands/mr.go
  commands/release.go
  commands/root.go
Labels: size/L

#143 feat: Add merge request todo command
  commands/mr_todo.go
Labels: size/M

#145 chore: Add benchmark to env config loading from FS
  internal/config/file_test.go
Labels: size/XS

#115 feat: Add `mr_for` command for creating MR and branch for issues
  commands/mr_for.go
Labels: size/L

#146 feat: Cache glab env config to improve overall command performance
  internal/config/file.go
Labels: size/M

#151 j mcavoy/trunk
  commands/mr_for.go
Labels: size/M

#109 fix: default GIT_REMOTE_URL_VAR to origin if not specified by user
  internal/git/git.go
Labels: size/S

#158 fix: Root commands flags not documented (in generated docs)
  commands/root.go
Labels: size/XS

#164 feat: clone project over ssh
  cmd/glab/main.go
  commands/repo_archive.go
  commands/repo_clone.go
  commands/user.go
Labels: size/M

#176 feat: label auto completion
  commands/issue_create.go
  commands/label_list.go
  internal/manip/manip.go
Labels: size/M

#171 feat: Add assignee filters for issue_list
  commands/issue_list.go
Labels: size/XS, waiting

#185 fix: set default url and nickname
  cmd/glab/main.go
Labels: size/XS
