Repository profclems/glab, pull requests merged in 2021-01, with the labels that each got.

#474 implement --assignee with relative and absolute additions
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: cmd: issue, size/L

#479 Rework assignee
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: size/XL

#480 fix(pkg/prompt): wrap survey prompts to allow stubs for test
  commands/cmdutils/cmdutils.go
  commands/issue/board/create/issue_board_create.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  internal/config/config.go
  pkg/prompt/prompt.go
Labels: size/M

#481 test(commands/cmdutils): add tests for PickMetadata()
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
Labels: kind: test, size/L

#482 Add testing for MilestonePrompt()
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
  internal/glrepo/resolver.go
  internal/glrepo/resolver_test.go
  pkg/prompt/prompt.go
Labels: kind: test, size/L

#484 refactor(internal/glrepo/resolver): remove unreachable code
  internal/glrepo/resolver.go
Labels: kind: cleanup, size/S

#485 Add more tests, use `pkg/prompt` for prompts
  internal/git/git.go
  internal/glrepo/resolver.go
  internal/glrepo/resolver_test.go
Labels: kind: Refactoring, kind: test, size/XL

#486 test(internal/glrepo/remote): test remoteNameSortingScore()
  internal/glrepo/remote_test.go
Labels: kind: test, size/M

#487 test(internal/glrepo/resolver): fix usage of assert()
  internal/glrepo/resolver_test.go
Labels: kind: test, size/M

#488 chore(ci/test): switch test job from GitLab CI to GitHub action
  .github/workflows/go.yml
  .gitlab-ci.yml
  commands/cmdtest/helper.go
Labels: size/M

#489 Resolver testing
  commands/cmdutils/cmdutils_test.go
  internal/glrepo/resolver.go
  internal/glrepo/resolver_test.go
  pkg/prompt/stubber.go
Labels: size/M

#491 test(internal/glrepo/resolver): add more tests
  internal/glrepo/resolver_test.go
Labels: kind: test, size/L

#490 chore(ci): ensure test runs on PRs
  .github/workflows/go.yml
  .github/workflows/lint.yml
Labels: area: automation, size/S

#493 chore(ci): fix go.yml workflow file
  .github/workflows/go.yml
Labels: size/XS

#492 No color
  internal/utils/color.go
  internal/utils/color_test.go
Labels: kind: test, size/M

#494 test(internal/glrepo/remote): add tests for FindByRepo()
  internal/glrepo/remote_test.go
  internal/glrepo/repo_test.go
Labels: kind: test, size/L

#495 test(internal/git/url): test bad URLs for ParseURL()
  internal/git/url_test.go
  internal/glrepo/remote_test.go
  internal/glrepo/repo_test.go
Labels: kind: test, size/M

#497 feat(internal/git): Add support for ssh_config Include directives
  internal/git/ssh_config.go
  internal/git/ssh_config_test.go
Labels: kind: enhancement, size/L

#498 test(internal/glinstance/host): test HostnameValidator()
  internal/glinstance/host_test.go
Labels: kind: test, size/M

#501 fix(commands/cmdutils/factory): use hostname from ssh config
  commands/cmdutils/factory.go
Labels: core, size/XS

#500 respect GITLAB_HOST when resolving remotes
  commands/cmdutils/factory.go
  commands/cmdutils/remote_resolver.go
  commands/cmdutils/remote_resolver_test.go
Labels: core, size/M

#502 test(internal/utils/display): implement tests for the basic functions
  internal/utils/display.go
  internal/utils/display_test.go
Labels: kind: test, size/L

#504 test(internal/utils/iostreams): add tests
  internal/config/file.go
  internal/config/file_test.go
  internal/config/local_config.go
  internal/utils/iostreams_test.go
Labels: kind: test, size/L

#506 style(commands/issue/list): refactor `issue list`
  commands/issue/issue.go
  commands/issue/list/issue_list.go
Labels: cmd: issue, kind: Refactoring, size/L

#505 Iostreams testing
  internal/config/local_config_test.go
  internal/config/writefile_test.go
  internal/utils/iostreams_test.go
Labels: kind: test, size/L

#507 refactor(commands/completion): always default to bash
  commands/completion/completion.go
Labels: kind: Refactoring, size/S

#509 test(commands/issue/list): add tests
  commands/issue/list/fixtures/issueList.json
  commands/issue/list/issue_list.go
  commands/issue/list/issue_list_test.go
  pkg/api/client.go
  pkg/httpmock/mocker.go
  pkg/httpmock/stub.go
Labels: kind: test, size/L

#510 refactor and add tests to `mr list`
  commands/mr/list/mr_list.go
  commands/mr/list/mr_list_test.go
  commands/mr/mr.go
Labels: kind: cleanup, kind: test, size/L

#511 test(cmd/glab/main): test path where debug is active
  cmd/glab/main_test.go
Labels: kind: test, size/S

#512 chore(rom/deb): Fix wrong install directory for rpm/deb
  .goreleaser.yml
Labels: size/XS

#517 fix: avoid printing unnecessary blank newlines
  cmd/glab/main.go
Labels: kind: fix, size/XS

#513 Unassign
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
Labels: cmd: issue, cmd: mr, kind: enhancement, size/S

#514 more tests
  internal/config/config_test.go
  internal/utils/manip_test.go
Labels: kind: test, size/M

#519 test(*): use backticks inside strings that use double-quotes
  commands/ci/trace/trace_test.go
  commands/cmdutils/cmdutils_test.go
  commands/completion/completion_test.go
  commands/mr/delete/mr_delete_test.go
  commands/mr/note/mr_note_create_test.go
  internal/glrepo/resolver_test.go
Labels: kind: test, size/M

#521 test: better tests for `note` on issue and mr
  commands/issue/note/issue_note_create.go
  commands/issue/note/issue_note_create_test.go
  commands/mr/note/mr_note_create.go
  commands/mr/note/mr_note_create_test.go
Labels: size/XL

#520 more friendly assignees experience
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  pkg/api/project.go
Labels: core, kind: enhancement, size/L

#518 Hostname validator
  commands/auth/login/login.go
  commands/auth/login/login_test.go
Labels: kind: test, size/M

#529 feat(commands/mr/checkout): accept OWNER:branch format for MRs
  commands/mr/checkout/mr_checkout.go
Labels: kind: enhancement, size/S

#527 Make LabelsPrompt() respect labels and not cache
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
Labels: size/L

#531 Tests for mrutils
  commands/mr/mrutils/mrutils.go
  commands/mr/mrutils/mrutils_test.go
Labels: size/L

#532 test(commands/mr/mrutils): use correct path in testing
  commands/mr/mrutils/mrutils_test.go
Labels: kind: test, size/M

#534 fix(issue/command): error casting glrepo.Interface to glrepo.Remote
  commands/issue/create/issue_create.go
Labels: kind: fix, size/XS

#535 Add feedback topic to help
  commands/root.go
Labels: size/XS

#525 chore(ci): add github action to get GitLab Issues
  .github/gitlab_issue_tpl.md
  .github/workflows/gitlab-issues-to-github.yml
  .gitlab/issue_templates/Bug.md
  .gitlab/issue_templates/Feature Request.md
  .gitlab/merge_request_templates/Default.md
Labels: area: automation, size/L

#536 clean up help topics
  commands/root.go
  commands/root_test.go
Labels: size/S

#537 feat(commands/issue): add EXAMPLES and ARGUMENTS
  commands/issue/issue.go
  commands/mr/mr.go
Labels: cmd: issue, cmd: mr, size/S

#543 fix(commands/mr/approve): use a more precise description for --sha
  commands/mr/approve/mr_approve.go
Labels: size/XS

#540 Add EXAMPLES for subcommands in `repo/project`
  commands/project/fork/fork.go
  commands/project/search/project_search.go
Labels: size/S

#539 Add EXAMPLES in subcommands of `label`
  commands/label/create/label_create.go
  commands/label/list/label_list.go
Labels: size/S

#538 Add more EXAMPLES for mr subcommands
  commands/mr/approve/mr_approve.go
  commands/mr/checkout/mr_checkout.go
  commands/mr/close/mr_close.go
  commands/mr/create/mr_create.go
  commands/mr/delete/mr_delete.go
  commands/mr/diff/diff.go
  commands/mr/issues/mr_issues.go
  commands/mr/list/mr_list.go
  commands/mr/merge/mr_merge.go
  commands/mr/rebase/mr_rebase.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/unsubscribe/mr_unsubscribe.go
Labels: size/L

#550 feat(commands/mr/utils): use Mangenta for merged MRs
  commands/mr/mrutils/mrutils.go
Labels: size/XS

#548 Issue list more
  commands/issue/list/issue_list.go
Labels: size/M

#545 feat(commands/mr/checkout): add --set-upstream-to flag
  commands/mr/checkout/mr_checkout.go
Labels: size/M

#549 Implement more listing options in `mr list`
  commands/mr/list/mr_list.go
Labels: size/M

#551 mr list
  commands/mr/list/mr_list.go
Labels: cmd: mr, kind: enhancement, size/S

#552 issue list
  commands/issue/list/issue_list.go
Labels: cmd: issue, kind: cleanup, kind: enhancement, size/M

#530 refactor(ci/view): Clean up ci view code
  commands/ci/trace/trace.go
  commands/ci/view/view.go
  commands/ci/view/view_test.go
Labels: size/L

#541 add EXAMPLES for subcommands of `issue` subcommand
  commands/issue/close/issue_close.go
  commands/issue/create/issue_create.go
  commands/issue/delete/issue_delete.go
  commands/issue/list/issue_list.go
  commands/issue/reopen/issue_reopen.go
  commands/issue/subscribe/issue_subscribe.go
  commands/issue/unsubscribe/issue_unsubscribe.go
  commands/issue/view/issue_view.go
Labels: size/M

#555 feat(commands/variable): add `variable set` command
  commands/root.go
  commands/variable/set/set.go
  commands/variable/set/set_test.go
  commands/variable/variable.go
  commands/variable/variable_test.go
  pkg/api/variable.go
Labels: kind: enhancement, size/XL

#559 feat(ci/view): Change color of failed pipelines that allow failure
  commands/ci/status/status.go
  commands/ci/view/view.go
Labels: size/S

#563 chore(dependency): Update github.com/rivo/tview to the newest version
  commands/ci/view/view.go
  commands/ci/view/view_test.go
  commands/issue/board/view/issue_board_view.go
  go.mod
  go.sum
Labels: size/XS

#560 chore(scripts): make quick installer script POSIX sh compliant
  README.md
  scripts/install.sh
  scripts/quick_install.sh
Labels: size/L

#566 Web for mr
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: size/S

#571 feat: add auth status command
  commands/auth/auth.go
  commands/auth/status/status.go
  commands/auth/status/status_test.go
  internal/utils/utils.go
  pkg/api/default.go
  pkg/api/default_test.go
  pkg/httpmock/mocker.go
  pkg/httpmock/stub.go
Labels: cmd: auth, kind: enhancement, size/XL

#575 refactor `issue view` package
  commands/issue/issue.go
  commands/issue/view/issue_view.go
  commands/issue/view/issue_view_test.go
Labels: size/L

#576 Fix unassign
  commands/issue/update/issue_update.go
  commands/mr/update/mr_update.go
Labels: size/S

#578 chore(deps): Update rivo/tview to newest verison
  go.mod
  go.sum
Labels: size/XS

#579 feat(commands/mr/update): add --target-branch flag
  commands/mr/update/mr_update.go
Labels: cmd: mr, kind: enhancement, size/XS

#572 docs: update alpine installtion for alpine > 3.13
  README.md
Labels: docs, size/S

#584 feat(commands/mr/create): use tracking branch as target branch if not given
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
  commands/mr/mr.go
Labels: cmd: mr, enhancement, size/XL

#581 feat(cmd/gen-docs): manpage generation from cobra
  .gitignore
  Makefile
  cmd/gen-docs/docs.go
Labels: docs, size/L

#577 Respect title desc
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
Labels: cmd: mr, size/M

#586 docs: (readme) touch up section referencing lab
  README.md
Labels: size/S

#585 Include more details to mr view
  commands/mr/view/mr_view.go
Labels: cmd: mr, enhancement, size/S

#590 add ci view instruction to mr view
  commands/mr/view/mr_view.go
Labels: size/XS

#591 fix repo override `-R | --repo`
  commands/cmdutils/repo_override.go
  internal/git/url.go
  internal/glrepo/repo.go
  internal/glrepo/repo_test.go
  internal/utils/utils.go
Labels: Fix, size/L

#595 Make linters effective
  .deepsource.toml
  .golangci.yml
  Makefile
  commands/alias/alias_test.go
  commands/auth/auth_test.go
  commands/ci/ci_test.go
  commands/ci/view/view.go
  commands/cmdtest/helper.go
  commands/help/help_test.go
  commands/issue/board/board_test.go
  commands/issue/issue_test.go
  commands/issue/list/issue_list.go
  commands/issue/view/issue_view_test.go
  commands/label/label_test.go
  commands/mr/create/mr_create.go
  commands/mr/list/mr_list.go
  commands/mr/mr_test.go
  commands/mr/view/mr_view_test.go
  commands/project/repo_test.go
  commands/release/list/release_list_test.go
  commands/release/release_test.go
  commands/root_test.go
  commands/user/user_test.go
  commands/variable/variable_test.go
  internal/config/file_test.go
Labels: size/L

#600 entire remove dependency on tcnksm/go-gitconfig
  commands/mr/checkout/mr_checkout.go
  go.mod
  go.sum
Labels: dependencies, size/XS
