Repository profclems/glab, pull requests merged in 2021-04, with the labels that each got.

#678 Fix: Allow for override of repo using OWNER/REPO
  cmd/glab/main.go
Labels: Fix, size/S

#681 feat(commands/api): add a reviewer filter to the mr list command
  api/merge_request.go
  commands/mr/list/mr_list.go
Labels: size/S

#689 CI status now has an option to show a more compact view.
  commands/ci/status/status.go
Labels: size/S

#690 Fix method not allowed when merging MR
  commands/ci/status/status.go
  commands/mr/merge/mr_merge.go
Labels: Fix, cmd: mr, size/M

#691 Fix segfault on ci list
  commands/ci/ciutils/utils.go
Labels: Fix, size/XS

#693 feat(mr/view): show reviewers of the merge request
  commands/mr/view/mr_view.go
  commands/mr/view/mr_view_test.go
Labels: size/S

#667 Fix hostnames resolution
  cmd/glab/main.go
Labels: size/XS

#695 feat: mr merge options
  commands/cmdutils/cmdutils.go
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
  commands/mr/merge/mr_merge.go
  commands/mr/mrutils/mrutils.go
  commands/mr/rebase/mr_rebase.go
  pkg/iostreams/iostreams.go
Labels: size/L

#694 feat(mr/view): update mr reviewers
  commands/cmdutils/cmdutils.go
  commands/mr/update/mr_update.go
Labels: size/M
