Repository profclems/glab, pull requests merged in 2021-02, with the labels that each got.

#602 adds a warning to avoid invoking `make test`
  .github/CONTRIBUTING.md
Labels: size/XS

#599 Add config-git descriptive interface reference
  README.md
  snap/snapcraft.yaml
Labels: Fix, platform-packaging, platform: Nix, size/XS

#598 feat: adds possibility to override host for API
  README.md
  api/client.go
  internal/config/config_type.go
  internal/config/config_type_test.go
Labels: core, enhancement, size/M

#601 Add prompt to git init on repo create. Fixes #569
  commands/project/create/project_create.go
Labels: enhancement, size/M

#606 Add MacPorts Instructions
  README.md
Labels: docs, platform-packaging, platform: MacOS, size/S

#608 Revert "Add config-git descriptive interface reference "
  README.md
  snap/snapcraft.yaml
Labels: size/XS

#615 fix: support deep nested subgroups in repo path
  internal/glrepo/repo.go
  internal/glrepo/repo_test.go
Labels: Fix, core, size/M

#621 fix(commands/mr/close): fix color used for a MR that was just closed
  commands/mr/close/mr_close.go
Labels: size/XS

#613 feat: Issue link on create
  api/issue.go
  commands/issue/create/issue_create.go
  commands/issue/create/issue_create_test.go
Labels: cmd: issue, enhancement, size/M

#622 allow more than one merge request to be defined for certain `mr` commands
  commands/mr/approve/mr_approve.go
  commands/mr/close/mr_close.go
  commands/mr/delete/mr_delete.go
  commands/mr/mrutils/mrutils.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/unsubscribe/mr_unsubscribe.go
Labels: size/L

#630 fix(mr): Use default branch on mr create
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
Labels: Fix, cmd: mr, size/S
