Repository profclems/glab, pull requests merged in 2021-11, with the labels that each got.

#865 fix: weird condition when prompt disabled
  commands/auth/login/login.go
Labels: size/XS

#898 Require Go 1.17+
  .github/workflows/go.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  go.mod
  go.sum
Labels: size/M

#900 mr: deprecate `mr for` command
  commands/mr/create/mr_create.go
  commands/mr/for/mr_for.go
Labels: size/L

#895 fix: add linebreak to check-output msg
  commands/update/check_update.go
  commands/update/check_update_test.go
Labels: size/XS

#871 fix(mr_create/issue_create): add encoding to title and change description encoding
  commands/issue/create/issue_create.go
  commands/mr/create/mr_create.go
Labels: size/S

#883 feat(mr): Only output MR URL to stdout if output is not a TTY
  commands/issue/close/issue_close.go
  commands/issue/create/issue_create.go
  commands/issue/issueutils/utils.go
  commands/issue/reopen/issue_reopen.go
  commands/issue/subscribe/issue_subscribe.go
  commands/issue/unsubscribe/issue_unsubscribe.go
  commands/issue/update/issue_update.go
  commands/mr/close/mr_close.go
  commands/mr/create/mr_create.go
  commands/mr/for/mr_for.go
  commands/mr/merge/mr_merge.go
  commands/mr/mrutils/mrutils.go
  commands/mr/mrutils/mrutils_test.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/unsubscribe/mr_unsubscribe.go
  commands/mr/update/mr_update.go
Labels: size/M
