Repository profclems/glab, pull requests merged in 2021-08, with the labels that each got.

#797 {go.mod, go.sum}: update dependencies
  commands/project/search/project_search.go
  go.mod
  go.sum
  pkg/iostreams/terminal.go
Labels: size/XS

#801 Apply --no-desc to every shell for completion
  commands/completion/completion.go
Labels: size/S

#807 Update README.md
  README.md
Labels: size/M

#808 commands/ssh-key: add commands for managing ssh keys
  commands/root.go
  commands/ssh-key/add/add.go
  commands/ssh-key/add/http.go
  commands/ssh-key/get/get.go
  commands/ssh-key/list/list.go
  commands/ssh-key/ssh-key.go
Labels: size/L

#799 feat: `variable list` command
  api/variable.go
  commands/variable/list/list.go
  commands/variable/variable.go
Labels: size/L

#811 commands: improve scriptability
  commands/project/create/project_create.go
  commands/ssh-key/get/get.go
Labels: size/XS

#817 goreleaser: fix nfpms install dir to use /usr/bin
  .goreleaser.yml
Labels: size/XS

#820 commands/ssh-key: fix wrong usage description in `ssh-key add`
  commands/ssh-key/add/add.go
Labels: size/XS, Fix

#823 fix: allow token or stdin in non interactive shells
  commands/auth/login/login.go
Labels: size/XS

#819 feat: fill MR desc with all commit bodies
  commands/mr/create/mr_create.go
  commands/mr/create/mr_create_test.go
Labels: size/M

#830 fix(pipeline): allow pipeline parameters to use colons in the values
  commands/ci/run/run.go
Labels: size/XS

#827 Add `--repo` flag to ssh-key subcommands
  commands/ssh-key/ssh-key.go
Labels: size/XS

#832 Handle paginated response in pipeline.GetPipelineJobs
  api/pipeline.go
Labels: size/S

#824 feat(cmdutils): Add project and group milestone prompt
  api/milestone.go
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
Labels: size/L
