Repository profclems/glab, pull requests merged in 2021-07, with the labels that each got.

#783 ci: drop dependabot
  .github/dependabot.yml
Labels: size/XS

#778 Add project view command
  api/repository_files.go
  commands/project/repo.go
  commands/project/view/project_view.go
  internal/glrepo/repo.go
  pkg/utils/utils.go
Labels: size/L

#785 auth/login: fix broken link to personal_access_token
  README.md
  commands/auth/login/login.go
  internal/config/config_type.go
  internal/config/config_type_test.go
Labels: size/S

#787 Fix `glab repo view` handling of branches
  commands/project/view/project_view.go
Labels: size/S

#788 Update incorrect parameters
  commands/mr/create/mr_create.go
Labels: size/XS

#790 feat mr: remove prefix in ID of MR just like Issue
  commands/mr/mrutils/mrutils.go
Labels: size/XS

#796 feat: switch to cobra's v2 bash completion
  commands/completion/completion.go
  go.mod
  go.sum
Labels: size/S
