Repository profclems/glab, pull requests merged in 2021-06, with the labels that each got.

#752 fix(ci/status): adding list of external jobs
  .gitignore
  api/commit.go
  commands/ci/ciutils/utils.go
  commands/ci/trace/trace.go
Labels: size/M

#746 chore(packaging): glab docker images
  .github/workflows/build_docs.yml
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile
  scripts/entrypoint.sh
Labels: size/L

#756 ci/action: fix release workflow
  .github/workflows/release.yml
Labels: size/S

#758 ci/action: fix release workflow
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/XS

#763 Fix MR operations for detached heads
  .github/CONTRIBUTING.md
  commands/mr/mrutils/mrutils.go
Labels: size/XS

#767 Respect job ID when passing it to the trace command
  api/pipeline.go
  commands/ci/ciutils/utils.go
  commands/ci/trace/trace.go
  commands/ci/view/view.go
Labels: size/M

#770 Homebrew
  .codecov.yml
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
Labels: size/L

#773 peek, not peak
  README.md
Labels: size/XS
