Repository profclems/glab, pull requests merged in 2021-05, with the labels that each got.

#696 Allow protocol override when overriding the default host
  cmd/glab/main.go
  internal/glinstance/host.go
Labels: Fix, size/M

#712 fix(glrepo): Remove side effect from RemoteURL
  internal/glrepo/repo.go
Labels: Fix, size/S

#714 ci status: improve scriptability
  commands/ci/status/status.go
  commands/ci/view/view.go
  pkg/utils/utils.go
Labels: size/S

#715 fix race condition on mr merge
  commands/mr/merge/mr_merge.go
  go.mod
  go.sum
Labels: size/S

#717 Add `-y|--yes` flag to skip submission prompt for `mr merge`
  commands/mr/merge/mr_merge.go
Labels: size/S

#720 Retry work
  api/merge_request.go
  commands/mr/merge/mr_merge.go
Labels: Fix, cmd: mr, size/M

#718 feat: git-credential store hack
  commands/auth/auth.go
  commands/auth/authutils/git_credentials.go
  commands/auth/authutils/git_credentials_test.go
  commands/auth/login/helper.go
  commands/auth/login/helper_test.go
  commands/auth/login/login.go
  commands/auth/status/status.go
  commands/config/config_test.go
  commands/mr/create/mr_create.go
  commands/project/clone/repo_clone.go
  commands/project/create/project_create.go
  commands/project/fork/fork.go
  internal/config/config_type.go
  internal/glrepo/repo.go
  internal/glrepo/repo_test.go
Labels: enhancement, size/XL

#730 Fix triggered jobs duration
  commands/ci/status/status.go
Labels: size/XS

#729 fix job viewing with detached pipelines
  api/pipeline.go
  commands/ci/status/status.go
  commands/ci/trace/trace.go
Labels: size/L

#445 feat: add new `release` commands to manage GitLab releases
  .gitignore
  api/client.go
  api/release.go
  cmd/glab/main.go
  cmd/glab/main_test.go
  commands/api/http.go
  commands/cmdutils/cmdutils_test.go
  commands/cmdutils/errors.go
  commands/release/create/create.go
  commands/release/delete/delete.go
  commands/release/download/download.go
  commands/release/list/release_list.go
  commands/release/release.go
  commands/release/releaseutils/releaseutils.go
  commands/release/releaseutils/upload/upload.go
  commands/release/upload/upload.go
  commands/release/view/view.go
  go.mod
  internal/glrepo/remote.go
  internal/glrepo/repo.go
  pkg/iostreams/icons.go
  pkg/iostreams/iostreams.go
  pkg/iostreams/logger.go
  pkg/utils/utils.go
Labels: cmd: release, enhancement, size/XXL

#742 fix: `:id` placeholder in `api` command
  commands/api/api.go
Labels: size/XS

#743 fix `mr merge` failing on detached branch
  commands/mr/mrutils/mrutils.go
Labels: size/S

#744 fix hostname validator to accept IPs and hosts with port
  commands/auth/login/login.go
  commands/auth/login/login_test.go
Labels: size/S
