Repository profclems/glab, pull requests merged in 2021-09, with the labels that each got.

#836 fix: error 404 when creating release
  commands/release/create/create.go
  commands/ssh-key/ssh-key.go
Labels: size/XS

#837 {go.mod,go.sum}: update dependencies
  api/project.go
  go.mod
  go.sum
Labels: deps, size/XS

#845 feat: allow reuse of glab in other CLI contexts
  api/client.go
  cmd/glab/main.go
  commands/api/api.go
  commands/auth/login/login.go
  commands/auth/status/status.go
  commands/cmdutils/factory.go
  commands/cmdutils/remote_resolver.go
  commands/config/config.go
  commands/project/clone/repo_clone.go
  commands/release/create/create.go
  commands/release/releaseutils/releaseutils.go
  commands/release/releaseutils/upload/upload.go
  commands/release/view/view.go
  internal/config/config_type.go
  internal/glrepo/repo.go
  pkg/glinstance/host.go
  pkg/glinstance/host_test.go
Labels: size/M
