Repository profclems/glab, pull requests merged in 2021-03, with the labels that each got.

#633 Create SECURITY.md
  SECURITY.md
Labels: size/XS

#627 feat(project.clone): add option to preserve namespaces by subdirectories
  commands/project/clone/repo_clone.go
Labels: cmd: repo/project, enhancement, size/S

#623 Draft: allow searching MRs by a state when it makes sense
  commands/mr/approve/mr_approve.go
  commands/mr/approvers/mr_approvers.go
  commands/mr/checkout/mr_checkout.go
  commands/mr/close/mr_close.go
  commands/mr/delete/mr_delete.go
  commands/mr/diff/diff.go
  commands/mr/issues/mr_issues.go
  commands/mr/merge/mr_merge.go
  commands/mr/mrutils/mrutils.go
  commands/mr/mrutils/mrutils_test.go
  commands/mr/note/mr_note_create.go
  commands/mr/rebase/mr_rebase.go
  commands/mr/reopen/mr_reopen.go
  commands/mr/revoke/mr_revoke.go
  commands/mr/subscribe/mr_subscribe.go
  commands/mr/todo/mr_todo.go
  commands/mr/unsubscribe/mr_unsubscribe.go
  commands/mr/update/mr_update.go
  commands/mr/view/mr_view.go
Labels: size/L

#639 fix: correct simple typo
  commands/project/search/project_search.go
  docs/source/repo/search.rst
  internal/glrepo/resolver_test.go
Labels: size/XS

#643 chore: add stale action workflow
  .github/workflows/stale.yml
Labels: size/S

#645 chore: ensure issues and PR are not closed in stale action
  .github/workflows/stale.yml
Labels: size/XS

#646 Override survey's choice of color for default values
  cmd/glab/main.go
  pkg/iostreams/color.go
  pkg/iostreams/iostreams.go
Labels: core, size/M

#650 Fix(pager): Resolve background color before staring pager
  commands/issue/view/issue_view.go
  commands/mr/view/mr_view.go
  go.mod
  go.sum
  pkg/iostreams/iostreams.go
  pkg/utils/utils.go
Labels: size/M

#653 Fix wrong reference to --autofill instead of --fill in docs
  commands/mr/create/mr_create.go
Labels: size/XS

#658 fix: respect GLAB_PAGER in config and env vars
  cmd/glab/main.go
Labels: size/XS

#659 Update README.md
  README.md
Labels: size/XS

#663 fix(commands/api): replace `:id` placeholder with project ID
  commands/api/api.go
Labels: Fix, cmd: api, size/S

#666 fix(board): Don't display closed issues in columns
  commands/issue/board/view/issue_board_view.go
Labels: size/S
