Repository profclems/glab, pull requests merged in 2021-12, with the labels that each got.

#921 feature: Read config directory from GLAB_CONFIG_DIR
  README.md
  commands/root.go
  internal/config/config_file.go
Labels: size/XS

#887 added push mirror and command
  api/mirror.go
  commands/project/mirror/project_mirror.go
  commands/project/repo.go
Labels: size/L, needs: testing

#930 fix: Write aliases to symlink if it exists
  internal/config/writefile.go
  internal/config/writefile_test.go
Labels: size/M
