Repository profclems/glab, pull requests merged in 2022-02, with the labels that each got.

#947 feat(api): Add issue time wrapper function
  api/issue.go
Labels: size/S

#950 feat(api): Add api wrappers for creating snippets
  api/snippets.go
Labels: size/M

#951 Change flag which causes errors in some shells
  scripts/install.sh
Labels: size/XS

#968 Specified Full Package name for winget Installation
  README.md
Labels: size/XS

#886 fix: Fail with a specific error when unauthenticated
  go.mod
  go.sum
  internal/glrepo/resolver.go
  internal/glrepo/resolver_test.go
Labels: size/M, stale

#949 feat(issue): Add time tracking functionality
  commands/issue/create/issue_create.go
Labels: size/M
