Repository profclems/glab, pull requests merged in 2022-01, with the labels that each got.

#937 chore: Update Arch README link to official repos
  README.md
Labels: size/XS

#931 feat: Add group flag to mr list command
  api/issue.go
  api/merge_request.go
  commands/issue/list/issue_list.go
  commands/issue/list/issue_list_test.go
  commands/mr/list/mr_list.go
  commands/mr/list/mr_list_test.go
Labels: size/L

#938 chore: Correct Arch Linux install command
  README.md
Labels: size/XS

#940 feat: accept GITLAB_ACCESS_TOKEN
  internal/config/config_type.go
Labels: size/XS

#942 feat(repo/clone): Add options for page and page size
  commands/project/clone/repo_clone.go
Labels: size/S

#936 Fix hyperlinks rendering in less
  pkg/iostreams/iostreams.go
Labels: size/XS

#910 Add artifact download command
  api/pipeline.go
  commands/ci/artifact/artifact.go
  commands/ci/ci.go
Labels: size/M, stale

#944 goreleaser: switch to `use` instead of `use_buildx`
  .goreleaser.yml
Labels: size/XS

#906 feat: add `repo list` command
  commands/project/list/list.go
  commands/project/repo.go
Labels: size/L

#946 fix: Example of glab ci list --status
  commands/ci/list/list.go
Labels: size/XS

#929 Add transfer command
  commands/cmdutils/cmdutils.go
  commands/project/repo.go
  commands/project/transfer/project_transfer.go
Labels: size/L

#927 fix: Don't show non-templates when asking chosing
  commands/cmdutils/cmdutils.go
  commands/cmdutils/cmdutils_test.go
  pkg/git/git.go
  test/testdata/.gitlab/issue_templates/.gitkeep-for-tests
  test/testdata/.gitlab/issue_templates/Bug.md
  test/testdata/.gitlab/issue_templates/Feature Request.md
  test/testdata/.gitlab/issue_templates/non-markdown-file-for-tests.txt
  test/testdata/.gitlab/merge_request_templates/Default.md
Labels: size/M, never-stale
